version: '3.4'

services:
  discord-cleanup-bot:
    image: git.bluemedia.dev/bluemedia/discord-cleanup-bot
    volumes:
      - bot-data:/data
    environment:
      - BOT_TOKEN=
    restart: unless-stopped

volumes:
  bot-data: