steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      pull_image: true
      registry: git.bluemedia.dev
      repo: git.bluemedia.dev/bluemedia/discord-cleanup-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
      tag: latest

  notify:
    image: deblan/woodpecker-email
    settings:
      dsn:
        from_secret: smtp_notify_dsn
      from:
        address:
          from_secret: smtp_notify_from_address
        name:
          from_secret: smtp_notify_from_name
      recipients:
        from_secret: smtp_notify_recipients
    when:
      - status: [ failure ]